### Numpy 

Numpy is functional Library For scientefic compunting in python. That the provides support array, matrix and mathamatic function of operator

In [1]:
## Creat array using numpy
## Creat 1D array

import numpy as np

arr1=np.array([1,3,4,5,6,7])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 3 4 5 6 7]
<class 'numpy.ndarray'>
(6,)


In [2]:
# crating 2D array in 1D Array
arr2 =np.array([1,3,4,5,6,7])
arr2.reshape(1,6) # 1 row and 5 column

array([[1, 3, 4, 5, 6, 7]])

In [3]:
# i use Nasted list / 2D Array

arr2 =np.array([[1,2,3,4,6,7,8],[8,9,10,11,12,13,14]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  6  7  8]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [4]:
np.arange(0,16,2).reshape(8,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14]])

In [5]:
# Some Inbuild function
np.ones((4,4)) # ones() are creating multiple line of array that be use in deep learning


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
## identy Matrix 
np.eye(3) # here is digonal function will be remine 0 like their output

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# Perticuller function name that be mostly to use

arr2 =np.array([[1,2,3,4,6,7,8],[8,9,10,11,12,13,14]])

print("Array :\n",arr2)
print("Number of Dimansion :",arr2.ndim)
print("The Data type :",arr2.dtype)
print("Size of array ",arr2.size)
print("Item size is (In Byte) :",arr2.itemsize)

Array :
 [[ 1  2  3  4  6  7  8]
 [ 8  9 10 11 12 13 14]]
Number of Dimansion : 2
The Data type : int64
Size of array  14
Item size is (In Byte) : 8


In [8]:
# Numpy Vector operation
arr1 =np.array([[1,2,3,4,5]])
arr2 =np.array([[8,9,10,11,12]])

# Element wise addition(
print("Addition",arr1+arr2)


# Element wise subtraction
print("subtraction",arr1-arr2)

# Element wise multiplication(
print("multiplication",arr1*arr2)

# Element wise divison
print("divison",arr1/arr2)

Addition [[ 9 11 13 15 17]]
subtraction [[-7 -7 -7 -7 -7]]
multiplication [[ 8 18 30 44 60]]
divison [[0.125      0.22222222 0.3        0.36363636 0.41666667]]


In [9]:
# Universal Function
arr1 =np.array([[1,2,3,4,5]])

# squre root
print(np.square(arr1))

## Exponesial 
print(np.exp(arr1)) #  Exponesial  is e^n  its use to ML

# use sin()
print(np.sin(arr1)) # here is sin() perform to the sine() values

# Log(ln) natrural
print(np.log(arr1))

[[ 1  4  9 16 25]]
[[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]]
[[0.         0.69314718 1.09861229 1.38629436 1.60943791]]


In [10]:
## Array slicing & indexing
arr1 =np.array([[1,2,3,4],[8,9,10,11],[12,13,14,15]])
print("Array : \n",arr1)


Array : 
 [[ 1  2  3  4]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
print(arr1[1:,1:2])

[[ 9]
 [13]]


In [12]:
# Row And Column Index
print(arr1[0][0])
print(arr1[0:2,2:])

1
[[ 3  4]
 [10 11]]


In [13]:
arr1[1:,2:]

array([[10, 11],
       [14, 15]])

In [14]:
# Modifying the address
arr1[0,0]=10
print(arr1)

[[10  2  3  4]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
arr1[1:]=100
print(arr1)

[[ 10   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [16]:
# Statical concepts
#  Normalization 

# to have a mean of 0 and standard divison of 1

data =np.array([1,2,3,4,5])

# Calculate the standard division 
mean =np.mean(data)
std_dev =np.std(data)

# normalizaition the data

normlized_data =(data-mean)/std_dev
print("normlized_data :" , normlized_data)


normlized_data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [17]:
# Finding the mean median and div

data =np.array([1,2,3,4,5])

# finding mean
mean =np.mean(data)
print(mean)

# Meadian

median =np.median(data)
print( "Median is :",median)

# Division
Div =np.std(data) 
print("Divison are :",Div)

# Variance 
var =np.var(data)
print("variance is that :",var)

3.0
Median is : 3.0
Divison are : 1.4142135623730951
variance is that : 2.0


In [18]:
# Logical Operation

data = np.array([1,2,3,45,6,7,8,9,45,8,2,33,4,3,62,15,3])

data[(data>=5) & ( data<=10)]


array([6, 7, 8, 9, 8])